name: Python CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install project
      run: |
        python setup.py install

    - name: Run tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE
        pytest tests/ --junitxml=test-results-${{ matrix.python-version }}.xml --html=test-report-${{ matrix.python-version }}.html --self-contained-html

    - name: Upload HTML test report
      uses: actions/upload-artifact@v4
      with:
        # 添加运行ID确保唯一性
        name: test-report-${{ matrix.python-version }}-${{ github.run_id }}
        path: test-report-${{ matrix.python-version }}.html

    - name: Upload JUnit test report
      uses: actions/upload-artifact@v4
      with:
        # 添加运行ID确保唯一性
        name: test-results-${{ matrix.python-version }}-${{ github.run_id }}
        path: test-results-${{ matrix.python-version }}.xml

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel

    - name: Upload package artifacts
      uses: actions/upload-artifact@v4
      with:
        name: python-package
        path: dist/*